# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/gta9pwifi-dev/android_kernel_samsung_sm6375-common
          kernel-branch: oem
          config: vendor/gta9pwifi_eur_open_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11-qpr3-s1
          aosp-clang-version: r383902b1
          disable-lto: true
